sudo: true
language: python
python:
    - "3.4"
    - "3.5"
    - "nightly"
before_install:
    - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) main universe"
    - sudo apt-add-repository "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.7 main"
    - wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
    - sudo apt-get update
    - sudo apt-get install libblas-dev liblapack-dev llvm-3.7 build-essential gfortran
    - sudo apt-get install llvm-3.7
install:
    - pip install -r requirements.txt
script:
    - nosetests --with-doctest
after_success:
    - bash <(curl -s https://codecov.io/bash)
