language: python
os:
  - linux
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - conda update --yes conda
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION
  - conda install --yes -c conda-forge `head -n 21 requirements.txt`
  - conda install --yes -c cpcloud npm
  - conda install --yes coverage
  - pip install sphinxcontrib-autoanysrc travis-sphinx codacy-coverage recommonmark
  - python setup.py install
script:
  - nosetests --with-coverage
  - coverage xml
  - travis-sphinx build
after_success:
  - codecov
  - coveralls
  - python-codacy-coverage -r coverage.xml
  - travis-sphinx deploy
