language: python

os:
  - linux

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda

install:
  - conda install -q python=$TRAVIS_PYTHON_VERSION
  - conda install -q -c conda-forge `cat requirements.txt`
  - conda install -q -c conda-forge pytables
  - pip install travis-sphinx codacy-coverage python-coveralls codecov
  - python setup.py install
  - ls -lisah
  - ls -lisah exa/
  - ls -lisah build/
  - ls -lisah /home/travis/build/avmarchenko/exa
  - ls -lisah /home/travis/build/avmarchenko/exa/exa/
  - ls -lisah /home/travis/build/avmarchenko/exa/exa/static
  - ls -lisah exa/static

script:
  - nosetests --with-coverage
  - coverage xml
  - travis-sphinx -n build

after_success:
  - codecov
  - coveralls
  - python-codacy-coverage -r coverage.xml
  - travis-sphinx -n deploy
