sudo: true
language: python
python:
    - "3.4"
    - "3.5"
    - "nightly"
before_install:
    - sudo apt-add-repository "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu precise main"
    - sudo apt-add-repository "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.7 main"
    - wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
    - sudo apt-get update
    - sudo apt-get install llvm-3.7
install:
    - pip install -r requirements.txt
script:
    - python exa/test/tester.py
after_success:
  - bash <(curl -s https://codecov.io/bash)
