language: python

os:
  - linux

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - git clone https://github.com/avmarchenko/exa
  - git clone https://github.com/avmarchenko/exatomic

install:
  - conda install -q python=$TRAVIS_PYTHON_VERSION
    #- conda install -q -c conda-forge `cat requirements.txt`
  - conda install -q -c conda-forge pytables
  - pip install travis-sphinx codacy-coverage python-coveralls codecov
  - cd exa; pip install -e .; cd ../;
  - cd exatomic; pip install -e .;
    #- python setup.py install

script:
  - nosetests --with-coverage
  - coverage xml
  - travis-sphinx -n build

after_success:
  - codecov
  - coveralls
  - python-codacy-coverage -r coverage.xml
  - travis-sphinx -n deploy
