sudo: false
language: python
python:
    - "3.4"
    - "3.5"
    - "nightly"
before_install:
    - sudo apt-get install llvm-3.7
install:
    - pip install -r requirements.txt
script:
    - python exa/test/tester.py
