matrix:
    include:
        - os: linux
          language: python
          python: 2.7
          env: PYTHONVER=2.7

        - os: linux
          language: python
          python: 3.5
          env: PYTHONVER=3.5

        - os: linux
          language: python
          python: 3.6
          env: PYTHONVER=3.6

install:
    - if [[ $TRAVIS_OS_NAME == "osx" ]]; then
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
      else
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi;
      echo "DONE"
    - bash miniconda.sh -b -p $HOME/miniconda
    - export NUMBA_DISABLE_JIT=1
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q -y --all
    - conda create -n test python=$PYTHONVER
    - source activate test
    - conda update -q -y --all
    - conda install -q -y -c conda-forge six numpy pandas pytables numba pyyaml
    - conda install -q -y -c conda-forge sphinx sphinx_rtd_theme ply sympy
    - conda install -q -y -c conda-forge pandoc pypandoc nbsphinx ipython seaborn
    - conda install -q -y -c conda-forge coveralls coverage pytest pytest-cov
    - pip install travis-sphinx codacy-coverage
    - pip install -e .

#script:
#    - export PYTHONDONTWRITEBYTECODE=1
#    - pytest --cov
#    - if [[ $TRAVIS_OS_NAME == "linux" ]] && [[ $PYTHONVER == 3.6 ]]; then
#          coverage run --source=exa setup.py test;
#          rm -rf docs/source/*.txt;
#          SPHINX_APIDOC_OPTIONS=members,undoc-members,show-inheritance sphinx-apidoc -eM -s txt -o docs/source/ exa *test*;
#          travis-sphinx build;
#      fi
#
#after_success:
#    - if [[ $TRAVIS_OS_NAME == "linux" ]] && [[ $PYTHONVER == 3.6 ]]; then
#          coveralls;
#          python-codacy-coverage -r coverage.xml;
#          travis-sphinx deploy;
#      fi
#
