language: python

matrix:
    include:
        - os: linux
          python: 2.7
          env: TOXENV=py2.7
        - os: linux
          python: 3.4
          env: TOXENV=py3.4
        - os: linux
          python: 3.5
          env: TOXENV=py3.5
        - os: linux
          python: 3.6
          env: TOXENV=py3.7
        - os: osx
          language: generic
          env: TOXENV=py2.7
        - os: osx
          language: generic
          env: TOXENV=py3.4
        - os: osx
          language: generic
          env: TOXENV=py3.5
        - os: osx
          language: generic
          env: TOXENV=py3.6

before_install:
  - if [ $TRAVIS_OS_NAME == "osx" ]; then
      wget http://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    else
      wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - sh miniconda.sh -b -p ~/miniconda
  - export NUMBA_DISABLE_JIT=1    # For coverage report
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q --all

# There are a lot of requirements here because we do coverage, testing, reporting, doc building
install:
  - conda install -q python=$TRAVIS_PYTHON_VERSION
  - conda install -q -c conda-forge six numpy pandas pytables numba sympy
  - conda install -q -c symengine symengine
  - conda install -q -c symengine python-symengine
  - conda install -q -c conda-forge sphinx sphinx_rtd_theme ply pandoc pypandoc nbsphinx
  - conda install -q -c conda-forge python-coveralls nose ipython
  - pip install travis-sphinx codacy-coverage coverage
  - pip install .

script:
  - nosetests --with-coverage
  - coverage xml
  - travis-sphinx -n build

after_success:
  - coveralls
  - python-codacy-coverage -r coverage.xml
  - travis-sphinx -n deploy
