matrix:
  include:
    - os: linux
      language: python
      python: 3.6
      env: PYTHONVER=3.6

    - os: linux
      language: python
      python: 3.7
      env: PYTHONVER=3.7

    - os: linux
      language: python
      python: 3.8
      env: PYTHONVER=3.8

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export NUMBA_DISABLE_JIT=1
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q -y --all
  - conda create -n test python=$PYTHONVER
  - source activate test
  - conda update -q -y --all
  - conda install -q -y networkx traitlets numpy pandas numba sympy pyyaml six
  - conda install -q -y pytest pytest-cov 
  - conda install -q -y -c conda-forge ipython sphinx nbsphinx sphinx_rtd_theme sphinxcontrib-napoleon
  - pip install travis-sphinx codacy-coverage
  - python setup.py install

script:
  - export PYTHONDONTWRITEBYTECODE=1
  - pytest test --cov
  - if [[ $PYTHONVER == 3.8 ]]; then
        coverage run -m pytest test;
        rm -rf docs/source/*.txt;
        SPHINX_APIDOC_OPTIONS=members,undoc-members,show-inheritance sphinx-apidoc -eM -s txt -o docs/source/ exa *test*;
        travis-sphinx build;
    fi
#
after_success:
  - if [[ $PYTHONVER == 3.8 ]]; then
        coveralls;
        python-codacy-coverage -r coverage.xml;
        travis-sphinx deploy;
    fi
