language: python
os:
  - linux
  - osx
matrix:
  allow_failures:
    - os: osx
python:
  - "2.7"
  - "3.4"
  - "3.5"
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - conda update --yes conda
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION
  - conda install --yes -c conda-forge `cat requirements.txt`
  - conda install --yes -c cpcloud npm
  - pip install sphinxcontrib-autoanysrc sphinx_rtd_theme coverage python-coveralls travis-sphinx codacy-coverage recommonmark
  - python setup.py install
script:
  - nosetests --with-coverage
  - coverage xml
  - travis-sphinx build
after_success:
  - codecov
  - coveralls
  - python-codacy-coverage -r coverage.xml
  - travis-sphinx deploy
