language: python

os:
  - linux

python:
  - "2.7"
  - "3.5"
  - "3.6"

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda

install:
  - conda install -q python=$TRAVIS_PYTHON_VERSION
  - conda install -q -c conda-forge `cat requirements.txt`
  - conda install -q -c conda-forge pytables python-coveralls
  - pip install travis-sphinx codacy-coverage coverage
  - pip install .

script:
  - nosetests --with-coverage
  - coverage xml
  - travis-sphinx -n build

after_success:
  - coveralls
  - python-codacy-coverage -r coverage.xml
  - travis-sphinx -n deploy
