language: python
python:
    - "3.4"
    - "3.5"
    - "nightly"
before_install:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda/bin:$PATH
    - conda update --yes conda
install:
    - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy matplotlib pandas sqlalchemy networkx sympy seaborn jupyter notebook==4.1 ipywidgets==4.1 ipyparallel sphinx nose
    - pip install sphinxcontrib-autoanysrc codecov
script:
    - nosetests --with-doctest --with-coverage
after_success:
    - codecov
