matrix:
  include:
    - os: linux
      language: python
      python: 2.7
      env: PYTHONVER=2.7
    - os: linux
      language: python
      python: 3.5
      env: PYTHONVER=3.5
    - os: linux
      language: python
      python: 3.6
      env: PYTHONVER=3.6
    - os: osx
      language: generic
      sudo: required
      env: PYTHONVER=2.7

#     brew update;
#     brew upgrade wget;
#     wget http://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      curl http://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -o miniconda.sh;
      sudo Xvfb :99 -ac -screen 0 1024x768x8; 
      echo ok;
    else
      wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      export DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 5;
    fi
  - sh miniconda.sh -b -p $HOME/miniconda
  - export NUMBA_DISABLE_JIT=1    # For coverage report
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q --all

# There are a lot of requirements here because we do coverage, testing, reporting, doc building
install:
  - conda create -n test python=$PYTHONVER
  - source activate test
  - conda install -q -c conda-forge six numpy pandas pytables numba sympy
  - conda install -q symengine -c symengine -c conda-forge
  - conda install -q python-symengine -c symengine -c conda-forge
  - conda install -q -c conda-forge sphinx sphinx_rtd_theme ply 
  - conda install -c conda-forge pandoc pypandoc nbsphinx
  - conda install -q -c conda-forge python-coveralls nose ipython
  - pip install travis-sphinx codacy-coverage coverage
  - pip install .

script:
  - nosetests --with-coverage
  - coverage xml
  - travis-sphinx -n build

after_success:
  - coveralls
  - python-codacy-coverage -r coverage.xml
  - travis-sphinx -n deploy
