envivronment:
  matrix:
    - PYTHON_VERSION: "3.6"
    - PYTHON_ARCH: "64"
    - CONDA_PY: "36"
    - CONDA_INSTALL_LOCN: "C:\\Miniconda36-x64"

install:
  - cmd: call %CONDA_INSTALL_LOCN%\Scripts\activate.bat
  - cmd: conda update -q -y --all
  - cmd: for /F "tokens=*" %i in (requirements.txt) do conda install -y -q -c conda-forge %i
  - cmd: conda install -q -y -c conda-forge pytables nodejs 
  - cmd: pip install travis-sphinx codacy-coverage python-coveralls

build:
  - cmd: pip install .

test_script:
  - cmd: nosetests --with-coverage 
  - cmd: coverage xml
  - cmd: travis-sphinx -n build

after_test:
  - cmd: coveralls
  - cmd: python-codacy-coverage -r coverage.xml
  - cmd: travis-sphinx -n deploy
