environment:
  # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
  # /E:ON and /V:ON options are not enabled in the batch script interpreter
  # See: http://stackoverflow.com/a/13751649/163740
  CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\misc\\appveyor\\run_with_env.cmd"

  matrix:
    # Pre-installed Python versions, which Appveyor may upgrade to
    # a later point release.
    # See: http://www.appveyor.com/docs/installed-software#python

    - PYTHON: "C:\\Miniconda-x64"
      PYTHON_ARCH: "64"
      CONDA_PLATFORM: "win-64"
      CONDA_PYSUFFIX: "py27"

    - PYTHON: "C:\\Miniconda"
      PYTHON_ARCH: "32"
      CONDA_PLATFORM: "win-32"
      CONDA_PYSUFFIX: "py27"

    - PYTHON: "C:\\Miniconda35-x64"
      PYTHON_ARCH: "64"
      CONDA_PLATFORM: "win-64"
      CONDA_PYSUFFIX: "py35"

    - PYTHON: "C:\\Miniconda35"
      PYTHON_ARCH: "32"
      CONDA_PLATFORM: "win-32"
      CONDA_PYSUFFIX: "py35"

    - PYTHON: "C:\\Miniconda36-x64"
      PYTHON_ARCH: "64"
      CONDA_PLATFORM: "win-64"
      CONDA_PYSUFFIX: "py36"

    - PYTHON: "C:\\Miniconda36"
      PYTHON_ARCH: "32"
      CONDA_PLATFORM: "win-32"
      CONDA_PYSUFFIX: "py36"

platform:
  - x64

install:
  # Use the pre-installed Miniconda for the desired arch
  - cmd: "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Install dependencies
  - cmd: conda config --set always_yes yes --set changeps1 no
  - cmd: conda update -q --all
  - cmd: conda install -q -c conda-forge six numpy pandas pytables numba
  - cmd: conda install -q -c conda-forge cmake cython sympy
  - cmd: conda install symengine -c symengine -c conda-forge
  - cmd: conda install -q python-symengine -c symengine -c conda-forge
  - cmd: conda install -q -c conda-forge nose
  - cmd: pip install .

build: false

test_script:
  - cmd: nosetests
