package:
    name: exa
    version: "0.4.0"

app:
    entry: exa

source:
    git_rev: v0.4.0
    git_url: https://github.com/exa-analytics/exa.git

requirements:
    build:
        - python x.x
        - numpy
        - scipy
        - matplotlib
        - seaborn
        - networkx
        - sqlalchemy
        - paramiko
        - pandas
        - h5py
        - sympy
        - notebook
        - ipywidgets
        - nose
        - numba
        - blosc
        - six
        - psutil
        - sphinx
        - sphinx_rtd_theme
        - pandoc
        - nbsphinx
        - coverage

    run:
        - numpy
        - scipy
        - matplotlib
        - seaborn
        - networkx
        - sqlalchemy
        - paramiko
        - pandas
        - h5py
        - sympy
        - notebook
        - ipywidgets
        - nose
        - numba
        - blosc
        - six
        - psutil

about:
    home: https://exa-analytics.github.io
    license: Apache-2.0
    license_file: LICENSE
    summary: A framework for data processing, analytics, and visualization.
